/**
 * Umi application route definition
 * @author Josh Ouyang 06/29/2020
 */

export const appRoutes = [
  {
    path: '/',
    component: '@/layouts/index',
    title: 'common.pageTitle.homepage',
    routes: [
      {
        path: '/',
        exact: true,
        menuDisplay: false,
        component: 'home/index',
        wrappers: ['@/wrappers/path', '@/wrappers/isLogin'],
      },
      {
        title: 'common.pageTitle.dataDiscovery',
        path: '/data-discovery',
        icon: 'FileTextOutlined',
        menuDisplay: true,
        showChildren: false,
        breadcrumbLink: true,
        permissions: ['DATA_DISCOVERY'],
        routes: [
          {
            title: 'common.pageTitle.dataDiscovery',
            path: '.',
            component: 'data-discovery/index',
            exact: true,
            breadcrumbLink: true,
            wrappers: ['@/wrappers/path', '@/wrappers/isLogin'],
          },
          {
            title: 'common.pageTitle.datasets',
            path: '/data-discovery/dataset',
            menuDisplay: true,
            icon: 'SnippetsOutlined',
            showChildren: false,
            breadcrumbLink: true,
            routes: [
              {
                title: 'common.pageTitle.datasets',
                path: '.',
                component: 'dataset/index',
                breadcrumbLink: true,
                exact: true,
                wrappers: ['@/wrappers/path', '@/wrappers/isLogin'],
              },
              {
                title: 'common.pageTitle.datasetDetail',
                path: '/data-discovery/dataset/:datasetId',
                component: 'dataset/dataset-detail/index',
                breadcrumbLink: true,
                exact: true,
                wrappers: ['@/wrappers/path', '@/wrappers/isLogin'],
              },
            ],
          },

          {
            title: 'common.pageTitle.glossary',
            path: '/data-discovery/glossary',
            menuDisplay: true,
            icon: 'SnippetsOutlined',
            showChildren: false,
            breadcrumbLink: true,
            routes: [
              {
                title: 'common.pageTitle.glossary',
                path: '.',
                component: 'glossary/index',
                breadcrumbLink: true,
                exact: true,
                wrappers: ['@/wrappers/path', '@/wrappers/isLogin'],
              },
              {
                title: 'common.pageTitle.glossaryCreate',
                path: '/data-discovery/glossary/create',
                component: 'glossary/glossary-detail/index',
                breadcrumbLink: true,
                exact: true,
                wrappers: ['@/wrappers/path', '@/wrappers/isLogin'],
              },
              {
                title: 'common.pageTitle.glossaryDetail',
                path: '/data-discovery/glossary/:glossaryId',
                component: 'glossary/glossary-detail/index',
                breadcrumbLink: true,
                exact: true,
                wrappers: ['@/wrappers/path', '@/wrappers/isLogin'],
              },
            ],
          },
        ],
      },
      {
        title: 'common.pageTitle.dataSettings',
        path: '/data-settings',
        menuDisplay: true,
        icon: 'SettingOutlined',
        component: 'data-settings/index',
        breadcrumbLink: true,
        permissions: ['DATA_DISCOVERY'],
        wrappers: ['@/wrappers/path', '@/wrappers/isLogin'],
      },
      {
        title: 'common.pageTitle.pdfExtract',
        path: '/pdf',
        menuDisplay: true,
        icon: 'FilePdfOutlined',
        permissions: ['PDF_GENERAL'],
        routes: [
          {
            title: 'common.pageTitle.pdfExtract',
            path: '.',
            component: 'pdf/pdfExtract/index',
            breadcrumbLink: true,
            exact: true,
            menuDisplay: true,
            wrappers: ['@/wrappers/path', '@/wrappers/isLogin'],
          },
          {
            title: 'common.pageTitle.pdfValidation',
            path: '/pdf/validation/:id',
            component: 'pdf/pdfValidation/index',
            breadcrumbLink: true,
            exact: true,
            menuDisplay: true,
            wrappers: ['@/wrappers/path', '@/wrappers/isLogin'],
          },
          {
            title: 'common.pageTitle.pdfBatchTask',
            path: '/pdf/batch-task/:id',
            component: 'pdf/pdfBatchTask/index',
            breadcrumbLink: true,
            exact: true,
            menuDisplay: true,
            wrappers: ['@/wrappers/path', '@/wrappers/isLogin'],
          },
          {
            title: 'common.pageTitle.pdfFileTask',
            path: '/pdf/batch-task/:batchTaskId/file-task/:fileTaskId',
            component: 'pdf/pdfFileTask/index',
            breadcrumbLink: true,
            exact: true,
            menuDisplay: true,
            wrappers: ['@/wrappers/path', '@/wrappers/isLogin'],
          },
          // {
          //   title: 'common.pageTitle.tryOut',
          //   path: '/pdf/tryout',
          //   component: 'pdf/tryout/index',
          //   breadcrumbLink: true,
          //   exact: true,
          //   menuDisplay: true,
          //   wrappers: ['@/wrappers/path', '@/wrappers/isLogin'],
          // },
          // {
          //   title: 'common.pageTitle.batchProcess',
          //   path: '.',
          //   component: 'pdf/batchProcess/index',
          //   breadcrumbLink: true,
          //   exact: true,
          //   menuDisplay: true,
          //   wrappers: ['@/wrappers/path', '@/wrappers/isLogin'],
          // },
          // {
          //   title: 'common.pageTitle.dumpJobs',
          //   path: '/pdf/dump-jobs',
          //   component: 'pdf/dumpJobs/index',
          //   breadcrumbLink: true,
          //   exact: true,
          //   menuDisplay: true,
          //   wrappers: ['@/wrappers/path', '@/wrappers/isLogin'],
          // },
        ],
      },
      {
        title: 'common.pageTitle.pdfExtract',
        path: '/pdf-extract',
        menuDisplay: true,
        icon: 'FilePdfOutlined',
        permissions: ['PDF_COA'],
        routes: [
          {
            title: 'common.pageTitle.pdfExtract',
            path: '.',
            component: 'pdf-new/index',
            breadcrumbLink: true,
            exact: true,
            menuDisplay: true,
            wrappers: ['@/wrappers/path', '@/wrappers/isLogin'],
          },
          {
            title: 'common.pageTitle.pdfExtract',
            path: './file-task/:fileTaskId',
            component: 'pdf/pdfFileTask/index',
            breadcrumbLink: true,
            exact: true,
            menuDisplay: true,
            wrappers: ['@/wrappers/path', '@/wrappers/isLogin'],
          },
        ],
      },
      {
        title: 'common.pageTitle.login',
        path: '/login',
        component: 'login/index',
        exact: true,
        wrappers: ['@/wrappers/path', '@/wrappers/isLogin'],
      },

      {
        path: '*',
        component: 'home/index',
        wrappers: ['@/wrappers/path', '@/wrappers/isLogin'],
      },
    ],
  },
];
