// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_role_scope.proto

package com.miotech.kun.security.facade.rpc;

public interface RoleOnSpecifiedModuleRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoleOnSpecifiedModuleResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string module = 2;</code>
   * @return The module.
   */
  java.lang.String getModule();
  /**
   * <code>string module = 2;</code>
   * @return The bytes for module.
   */
  com.google.protobuf.ByteString
      getModuleBytes();

  /**
   * <code>string rolename = 3;</code>
   * @return The rolename.
   */
  java.lang.String getRolename();
  /**
   * <code>string rolename = 3;</code>
   * @return The bytes for rolename.
   */
  com.google.protobuf.ByteString
      getRolenameBytes();
}
