// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_role_scope.proto

package com.miotech.kun.security.facade.rpc;

public interface ScopeRoleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ScopeRole)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string rolename = 1;</code>
   * @return The rolename.
   */
  java.lang.String getRolename();
  /**
   * <code>string rolename = 1;</code>
   * @return The bytes for rolename.
   */
  com.google.protobuf.ByteString
      getRolenameBytes();

  /**
   * <code>string sourceSystemId = 2;</code>
   * @return The sourceSystemId.
   */
  java.lang.String getSourceSystemId();
  /**
   * <code>string sourceSystemId = 2;</code>
   * @return The bytes for sourceSystemId.
   */
  com.google.protobuf.ByteString
      getSourceSystemIdBytes();
}
