// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_role_scope.proto

package com.miotech.kun.security.facade.rpc;

/**
 * Protobuf type {@code ScopeRole}
 */
public final class ScopeRole extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ScopeRole)
    ScopeRoleOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ScopeRole.newBuilder() to construct.
  private ScopeRole(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ScopeRole() {
    rolename_ = "";
    sourceSystemId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ScopeRole();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ScopeRole(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            rolename_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            sourceSystemId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.miotech.kun.security.facade.rpc.SecurityProto.internal_static_ScopeRole_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.miotech.kun.security.facade.rpc.SecurityProto.internal_static_ScopeRole_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.miotech.kun.security.facade.rpc.ScopeRole.class, com.miotech.kun.security.facade.rpc.ScopeRole.Builder.class);
  }

  public static final int ROLENAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object rolename_;
  /**
   * <code>string rolename = 1;</code>
   * @return The rolename.
   */
  @java.lang.Override
  public java.lang.String getRolename() {
    java.lang.Object ref = rolename_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rolename_ = s;
      return s;
    }
  }
  /**
   * <code>string rolename = 1;</code>
   * @return The bytes for rolename.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRolenameBytes() {
    java.lang.Object ref = rolename_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rolename_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCESYSTEMID_FIELD_NUMBER = 2;
  private volatile java.lang.Object sourceSystemId_;
  /**
   * <code>string sourceSystemId = 2;</code>
   * @return The sourceSystemId.
   */
  @java.lang.Override
  public java.lang.String getSourceSystemId() {
    java.lang.Object ref = sourceSystemId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceSystemId_ = s;
      return s;
    }
  }
  /**
   * <code>string sourceSystemId = 2;</code>
   * @return The bytes for sourceSystemId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceSystemIdBytes() {
    java.lang.Object ref = sourceSystemId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceSystemId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rolename_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, rolename_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceSystemId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sourceSystemId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rolename_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, rolename_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceSystemId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sourceSystemId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.miotech.kun.security.facade.rpc.ScopeRole)) {
      return super.equals(obj);
    }
    com.miotech.kun.security.facade.rpc.ScopeRole other = (com.miotech.kun.security.facade.rpc.ScopeRole) obj;

    if (!getRolename()
        .equals(other.getRolename())) return false;
    if (!getSourceSystemId()
        .equals(other.getSourceSystemId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROLENAME_FIELD_NUMBER;
    hash = (53 * hash) + getRolename().hashCode();
    hash = (37 * hash) + SOURCESYSTEMID_FIELD_NUMBER;
    hash = (53 * hash) + getSourceSystemId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.miotech.kun.security.facade.rpc.ScopeRole parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.miotech.kun.security.facade.rpc.ScopeRole parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.miotech.kun.security.facade.rpc.ScopeRole parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.miotech.kun.security.facade.rpc.ScopeRole parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.miotech.kun.security.facade.rpc.ScopeRole parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.miotech.kun.security.facade.rpc.ScopeRole parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.miotech.kun.security.facade.rpc.ScopeRole parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.miotech.kun.security.facade.rpc.ScopeRole parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.miotech.kun.security.facade.rpc.ScopeRole parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.miotech.kun.security.facade.rpc.ScopeRole parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.miotech.kun.security.facade.rpc.ScopeRole parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.miotech.kun.security.facade.rpc.ScopeRole parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.miotech.kun.security.facade.rpc.ScopeRole prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ScopeRole}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ScopeRole)
      com.miotech.kun.security.facade.rpc.ScopeRoleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.miotech.kun.security.facade.rpc.SecurityProto.internal_static_ScopeRole_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.miotech.kun.security.facade.rpc.SecurityProto.internal_static_ScopeRole_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.miotech.kun.security.facade.rpc.ScopeRole.class, com.miotech.kun.security.facade.rpc.ScopeRole.Builder.class);
    }

    // Construct using com.miotech.kun.security.facade.rpc.ScopeRole.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      rolename_ = "";

      sourceSystemId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.miotech.kun.security.facade.rpc.SecurityProto.internal_static_ScopeRole_descriptor;
    }

    @java.lang.Override
    public com.miotech.kun.security.facade.rpc.ScopeRole getDefaultInstanceForType() {
      return com.miotech.kun.security.facade.rpc.ScopeRole.getDefaultInstance();
    }

    @java.lang.Override
    public com.miotech.kun.security.facade.rpc.ScopeRole build() {
      com.miotech.kun.security.facade.rpc.ScopeRole result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.miotech.kun.security.facade.rpc.ScopeRole buildPartial() {
      com.miotech.kun.security.facade.rpc.ScopeRole result = new com.miotech.kun.security.facade.rpc.ScopeRole(this);
      result.rolename_ = rolename_;
      result.sourceSystemId_ = sourceSystemId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.miotech.kun.security.facade.rpc.ScopeRole) {
        return mergeFrom((com.miotech.kun.security.facade.rpc.ScopeRole)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.miotech.kun.security.facade.rpc.ScopeRole other) {
      if (other == com.miotech.kun.security.facade.rpc.ScopeRole.getDefaultInstance()) return this;
      if (!other.getRolename().isEmpty()) {
        rolename_ = other.rolename_;
        onChanged();
      }
      if (!other.getSourceSystemId().isEmpty()) {
        sourceSystemId_ = other.sourceSystemId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.miotech.kun.security.facade.rpc.ScopeRole parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.miotech.kun.security.facade.rpc.ScopeRole) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object rolename_ = "";
    /**
     * <code>string rolename = 1;</code>
     * @return The rolename.
     */
    public java.lang.String getRolename() {
      java.lang.Object ref = rolename_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rolename_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string rolename = 1;</code>
     * @return The bytes for rolename.
     */
    public com.google.protobuf.ByteString
        getRolenameBytes() {
      java.lang.Object ref = rolename_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rolename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string rolename = 1;</code>
     * @param value The rolename to set.
     * @return This builder for chaining.
     */
    public Builder setRolename(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      rolename_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string rolename = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRolename() {
      
      rolename_ = getDefaultInstance().getRolename();
      onChanged();
      return this;
    }
    /**
     * <code>string rolename = 1;</code>
     * @param value The bytes for rolename to set.
     * @return This builder for chaining.
     */
    public Builder setRolenameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      rolename_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sourceSystemId_ = "";
    /**
     * <code>string sourceSystemId = 2;</code>
     * @return The sourceSystemId.
     */
    public java.lang.String getSourceSystemId() {
      java.lang.Object ref = sourceSystemId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceSystemId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sourceSystemId = 2;</code>
     * @return The bytes for sourceSystemId.
     */
    public com.google.protobuf.ByteString
        getSourceSystemIdBytes() {
      java.lang.Object ref = sourceSystemId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceSystemId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sourceSystemId = 2;</code>
     * @param value The sourceSystemId to set.
     * @return This builder for chaining.
     */
    public Builder setSourceSystemId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceSystemId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sourceSystemId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceSystemId() {
      
      sourceSystemId_ = getDefaultInstance().getSourceSystemId();
      onChanged();
      return this;
    }
    /**
     * <code>string sourceSystemId = 2;</code>
     * @param value The bytes for sourceSystemId to set.
     * @return This builder for chaining.
     */
    public Builder setSourceSystemIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceSystemId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ScopeRole)
  }

  // @@protoc_insertion_point(class_scope:ScopeRole)
  private static final com.miotech.kun.security.facade.rpc.ScopeRole DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.miotech.kun.security.facade.rpc.ScopeRole();
  }

  public static com.miotech.kun.security.facade.rpc.ScopeRole getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ScopeRole>
      PARSER = new com.google.protobuf.AbstractParser<ScopeRole>() {
    @java.lang.Override
    public ScopeRole parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ScopeRole(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ScopeRole> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ScopeRole> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.miotech.kun.security.facade.rpc.ScopeRole getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

