// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_role_scope.proto

package com.miotech.kun.security.facade.rpc;

public final class SecurityProto {
  private SecurityProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoleOnSpecifiedModuleReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoleOnSpecifiedModuleReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoleOnSpecifiedModuleResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoleOnSpecifiedModuleResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoleOnSpecifiedResourcesReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoleOnSpecifiedResourcesReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ScopeRole_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ScopeRole_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoleOnSpecifiedResourcesResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoleOnSpecifiedResourcesResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateScopeOnSpecifiedRoleReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateScopeOnSpecifiedRoleReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UsersOnSpecifiedRoleReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UsersOnSpecifiedRoleReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UsersOnSpecifiedRoleResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UsersOnSpecifiedRoleResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025user_role_scope.proto\032\033google/protobuf" +
      "/empty.proto\"<\n\030RoleOnSpecifiedModuleReq" +
      "\022\020\n\010username\030\001 \001(\t\022\016\n\006module\030\002 \001(\t\"P\n\031Ro" +
      "leOnSpecifiedModuleResp\022\020\n\010username\030\001 \001(" +
      "\t\022\016\n\006module\030\002 \001(\t\022\021\n\trolenames\030\003 \003(\t\"X\n\033" +
      "RoleOnSpecifiedResourcesReq\022\020\n\010username\030" +
      "\001 \001(\t\022\016\n\006module\030\002 \001(\t\022\027\n\017sourceSystemIds" +
      "\030\003 \003(\t\"5\n\tScopeRole\022\020\n\010rolename\030\001 \001(\t\022\026\n" +
      "\016sourceSystemId\030\002 \001(\t\"`\n\034RoleOnSpecified" +
      "ResourcesResp\022\020\n\010username\030\001 \001(\t\022\016\n\006modul" +
      "e\030\002 \001(\t\022\036\n\nscopeRoles\030\003 \003(\0132\n.ScopeRole\"" +
      "l\n\035UpdateScopeOnSpecifiedRoleReq\022\020\n\010user" +
      "name\030\001 \001(\t\022\020\n\010rolename\030\002 \001(\t\022\016\n\006module\030\003" +
      " \001(\t\022\027\n\017sourceSystemIds\030\004 \003(\t\"S\n\027UsersOn" +
      "SpecifiedRoleReq\022\016\n\006module\030\001 \001(\t\022\020\n\010role" +
      "name\030\002 \001(\t\022\026\n\016sourceSystemId\030\003 \001(\t\"-\n\030Us" +
      "ersOnSpecifiedRoleResp\022\021\n\tusernames\030\001 \003(" +
      "\t2\265\003\n\010Security\022O\n\030findUsersOnSpecifiedRo" +
      "le\022\030.UsersOnSpecifiedRoleReq\032\031.UsersOnSp" +
      "ecifiedRoleResp\022R\n\031findRoleOnSpecifiedMo" +
      "dule\022\031.RoleOnSpecifiedModuleReq\032\032.RoleOn" +
      "SpecifiedModuleResp\022[\n\034findRoleOnSpecifi" +
      "edResources\022\034.RoleOnSpecifiedResourcesRe" +
      "q\032\035.RoleOnSpecifiedResourcesResp\022Q\n\027addS" +
      "copeOnSpecifiedRole\022\036.UpdateScopeOnSpeci" +
      "fiedRoleReq\032\026.google.protobuf.Empty\022T\n\032d" +
      "eleteScopeOnSpecifiedRole\022\036.UpdateScopeO" +
      "nSpecifiedRoleReq\032\026.google.protobuf.Empt" +
      "yB6\n#com.miotech.kun.security.facade.rpc" +
      "B\rSecurityProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_RoleOnSpecifiedModuleReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RoleOnSpecifiedModuleReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoleOnSpecifiedModuleReq_descriptor,
        new java.lang.String[] { "Username", "Module", });
    internal_static_RoleOnSpecifiedModuleResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RoleOnSpecifiedModuleResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoleOnSpecifiedModuleResp_descriptor,
        new java.lang.String[] { "Username", "Module", "Rolenames", });
    internal_static_RoleOnSpecifiedResourcesReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RoleOnSpecifiedResourcesReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoleOnSpecifiedResourcesReq_descriptor,
        new java.lang.String[] { "Username", "Module", "SourceSystemIds", });
    internal_static_ScopeRole_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ScopeRole_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ScopeRole_descriptor,
        new java.lang.String[] { "Rolename", "SourceSystemId", });
    internal_static_RoleOnSpecifiedResourcesResp_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_RoleOnSpecifiedResourcesResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoleOnSpecifiedResourcesResp_descriptor,
        new java.lang.String[] { "Username", "Module", "ScopeRoles", });
    internal_static_UpdateScopeOnSpecifiedRoleReq_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_UpdateScopeOnSpecifiedRoleReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateScopeOnSpecifiedRoleReq_descriptor,
        new java.lang.String[] { "Username", "Rolename", "Module", "SourceSystemIds", });
    internal_static_UsersOnSpecifiedRoleReq_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_UsersOnSpecifiedRoleReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UsersOnSpecifiedRoleReq_descriptor,
        new java.lang.String[] { "Module", "Rolename", "SourceSystemId", });
    internal_static_UsersOnSpecifiedRoleResp_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_UsersOnSpecifiedRoleResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UsersOnSpecifiedRoleResp_descriptor,
        new java.lang.String[] { "Usernames", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
