// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_role_scope.proto

package com.miotech.kun.security.facade.rpc;

public interface UsersOnSpecifiedRoleRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UsersOnSpecifiedRoleResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string usernames = 1;</code>
   * @return A list containing the usernames.
   */
  java.util.List<java.lang.String>
      getUsernamesList();
  /**
   * <code>repeated string usernames = 1;</code>
   * @return The count of usernames.
   */
  int getUsernamesCount();
  /**
   * <code>repeated string usernames = 1;</code>
   * @param index The index of the element to return.
   * @return The usernames at the given index.
   */
  java.lang.String getUsernames(int index);
  /**
   * <code>repeated string usernames = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the usernames at the given index.
   */
  com.google.protobuf.ByteString
      getUsernamesBytes(int index);
}
