// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_role_scope.proto

package com.miotech.kun.security.facade.rpc;

/**
 * Protobuf type {@code UsersOnSpecifiedRoleResp}
 */
public final class UsersOnSpecifiedRoleResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:UsersOnSpecifiedRoleResp)
    UsersOnSpecifiedRoleRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UsersOnSpecifiedRoleResp.newBuilder() to construct.
  private UsersOnSpecifiedRoleResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UsersOnSpecifiedRoleResp() {
    usernames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UsersOnSpecifiedRoleResp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UsersOnSpecifiedRoleResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              usernames_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            usernames_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        usernames_ = usernames_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.miotech.kun.security.facade.rpc.SecurityProto.internal_static_UsersOnSpecifiedRoleResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.miotech.kun.security.facade.rpc.SecurityProto.internal_static_UsersOnSpecifiedRoleResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp.class, com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp.Builder.class);
  }

  public static final int USERNAMES_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList usernames_;
  /**
   * <code>repeated string usernames = 1;</code>
   * @return A list containing the usernames.
   */
  public com.google.protobuf.ProtocolStringList
      getUsernamesList() {
    return usernames_;
  }
  /**
   * <code>repeated string usernames = 1;</code>
   * @return The count of usernames.
   */
  public int getUsernamesCount() {
    return usernames_.size();
  }
  /**
   * <code>repeated string usernames = 1;</code>
   * @param index The index of the element to return.
   * @return The usernames at the given index.
   */
  public java.lang.String getUsernames(int index) {
    return usernames_.get(index);
  }
  /**
   * <code>repeated string usernames = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the usernames at the given index.
   */
  public com.google.protobuf.ByteString
      getUsernamesBytes(int index) {
    return usernames_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < usernames_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, usernames_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < usernames_.size(); i++) {
        dataSize += computeStringSizeNoTag(usernames_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getUsernamesList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp)) {
      return super.equals(obj);
    }
    com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp other = (com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp) obj;

    if (!getUsernamesList()
        .equals(other.getUsernamesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUsernamesCount() > 0) {
      hash = (37 * hash) + USERNAMES_FIELD_NUMBER;
      hash = (53 * hash) + getUsernamesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UsersOnSpecifiedRoleResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UsersOnSpecifiedRoleResp)
      com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.miotech.kun.security.facade.rpc.SecurityProto.internal_static_UsersOnSpecifiedRoleResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.miotech.kun.security.facade.rpc.SecurityProto.internal_static_UsersOnSpecifiedRoleResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp.class, com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp.Builder.class);
    }

    // Construct using com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      usernames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.miotech.kun.security.facade.rpc.SecurityProto.internal_static_UsersOnSpecifiedRoleResp_descriptor;
    }

    @java.lang.Override
    public com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp getDefaultInstanceForType() {
      return com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp.getDefaultInstance();
    }

    @java.lang.Override
    public com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp build() {
      com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp buildPartial() {
      com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp result = new com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        usernames_ = usernames_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.usernames_ = usernames_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp) {
        return mergeFrom((com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp other) {
      if (other == com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp.getDefaultInstance()) return this;
      if (!other.usernames_.isEmpty()) {
        if (usernames_.isEmpty()) {
          usernames_ = other.usernames_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureUsernamesIsMutable();
          usernames_.addAll(other.usernames_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList usernames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureUsernamesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        usernames_ = new com.google.protobuf.LazyStringArrayList(usernames_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string usernames = 1;</code>
     * @return A list containing the usernames.
     */
    public com.google.protobuf.ProtocolStringList
        getUsernamesList() {
      return usernames_.getUnmodifiableView();
    }
    /**
     * <code>repeated string usernames = 1;</code>
     * @return The count of usernames.
     */
    public int getUsernamesCount() {
      return usernames_.size();
    }
    /**
     * <code>repeated string usernames = 1;</code>
     * @param index The index of the element to return.
     * @return The usernames at the given index.
     */
    public java.lang.String getUsernames(int index) {
      return usernames_.get(index);
    }
    /**
     * <code>repeated string usernames = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the usernames at the given index.
     */
    public com.google.protobuf.ByteString
        getUsernamesBytes(int index) {
      return usernames_.getByteString(index);
    }
    /**
     * <code>repeated string usernames = 1;</code>
     * @param index The index to set the value at.
     * @param value The usernames to set.
     * @return This builder for chaining.
     */
    public Builder setUsernames(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureUsernamesIsMutable();
      usernames_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string usernames = 1;</code>
     * @param value The usernames to add.
     * @return This builder for chaining.
     */
    public Builder addUsernames(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureUsernamesIsMutable();
      usernames_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string usernames = 1;</code>
     * @param values The usernames to add.
     * @return This builder for chaining.
     */
    public Builder addAllUsernames(
        java.lang.Iterable<java.lang.String> values) {
      ensureUsernamesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, usernames_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string usernames = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsernames() {
      usernames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string usernames = 1;</code>
     * @param value The bytes of the usernames to add.
     * @return This builder for chaining.
     */
    public Builder addUsernamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureUsernamesIsMutable();
      usernames_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:UsersOnSpecifiedRoleResp)
  }

  // @@protoc_insertion_point(class_scope:UsersOnSpecifiedRoleResp)
  private static final com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp();
  }

  public static com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UsersOnSpecifiedRoleResp>
      PARSER = new com.google.protobuf.AbstractParser<UsersOnSpecifiedRoleResp>() {
    @java.lang.Override
    public UsersOnSpecifiedRoleResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UsersOnSpecifiedRoleResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UsersOnSpecifiedRoleResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UsersOnSpecifiedRoleResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.miotech.kun.security.facade.rpc.UsersOnSpecifiedRoleResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

