// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_role_scope.proto

package com.miotech.kun.security.facade.rpc;

/**
 * Protobuf type {@code UserRoleResp}
 */
public final class UserRoleResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:UserRoleResp)
    UserRoleRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserRoleResp.newBuilder() to construct.
  private UserRoleResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserRoleResp() {
    username_ = "";
    module_ = "";
    scopeRoles_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserRoleResp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserRoleResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            username_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            module_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              scopeRoles_ = new java.util.ArrayList<com.miotech.kun.security.facade.rpc.ScopeRole>();
              mutable_bitField0_ |= 0x00000001;
            }
            scopeRoles_.add(
                input.readMessage(com.miotech.kun.security.facade.rpc.ScopeRole.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        scopeRoles_ = java.util.Collections.unmodifiableList(scopeRoles_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.miotech.kun.security.facade.rpc.SecurityProto.internal_static_UserRoleResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.miotech.kun.security.facade.rpc.SecurityProto.internal_static_UserRoleResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.miotech.kun.security.facade.rpc.UserRoleResp.class, com.miotech.kun.security.facade.rpc.UserRoleResp.Builder.class);
  }

  public static final int USERNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object username_;
  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODULE_FIELD_NUMBER = 2;
  private volatile java.lang.Object module_;
  /**
   * <code>string module = 2;</code>
   * @return The module.
   */
  @java.lang.Override
  public java.lang.String getModule() {
    java.lang.Object ref = module_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      module_ = s;
      return s;
    }
  }
  /**
   * <code>string module = 2;</code>
   * @return The bytes for module.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModuleBytes() {
    java.lang.Object ref = module_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      module_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCOPEROLES_FIELD_NUMBER = 3;
  private java.util.List<com.miotech.kun.security.facade.rpc.ScopeRole> scopeRoles_;
  /**
   * <code>repeated .ScopeRole scopeRoles = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.miotech.kun.security.facade.rpc.ScopeRole> getScopeRolesList() {
    return scopeRoles_;
  }
  /**
   * <code>repeated .ScopeRole scopeRoles = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.miotech.kun.security.facade.rpc.ScopeRoleOrBuilder> 
      getScopeRolesOrBuilderList() {
    return scopeRoles_;
  }
  /**
   * <code>repeated .ScopeRole scopeRoles = 3;</code>
   */
  @java.lang.Override
  public int getScopeRolesCount() {
    return scopeRoles_.size();
  }
  /**
   * <code>repeated .ScopeRole scopeRoles = 3;</code>
   */
  @java.lang.Override
  public com.miotech.kun.security.facade.rpc.ScopeRole getScopeRoles(int index) {
    return scopeRoles_.get(index);
  }
  /**
   * <code>repeated .ScopeRole scopeRoles = 3;</code>
   */
  @java.lang.Override
  public com.miotech.kun.security.facade.rpc.ScopeRoleOrBuilder getScopeRolesOrBuilder(
      int index) {
    return scopeRoles_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(module_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, module_);
    }
    for (int i = 0; i < scopeRoles_.size(); i++) {
      output.writeMessage(3, scopeRoles_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(module_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, module_);
    }
    for (int i = 0; i < scopeRoles_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, scopeRoles_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.miotech.kun.security.facade.rpc.UserRoleResp)) {
      return super.equals(obj);
    }
    com.miotech.kun.security.facade.rpc.UserRoleResp other = (com.miotech.kun.security.facade.rpc.UserRoleResp) obj;

    if (!getUsername()
        .equals(other.getUsername())) return false;
    if (!getModule()
        .equals(other.getModule())) return false;
    if (!getScopeRolesList()
        .equals(other.getScopeRolesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    hash = (37 * hash) + MODULE_FIELD_NUMBER;
    hash = (53 * hash) + getModule().hashCode();
    if (getScopeRolesCount() > 0) {
      hash = (37 * hash) + SCOPEROLES_FIELD_NUMBER;
      hash = (53 * hash) + getScopeRolesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.miotech.kun.security.facade.rpc.UserRoleResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.miotech.kun.security.facade.rpc.UserRoleResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.miotech.kun.security.facade.rpc.UserRoleResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.miotech.kun.security.facade.rpc.UserRoleResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.miotech.kun.security.facade.rpc.UserRoleResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.miotech.kun.security.facade.rpc.UserRoleResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.miotech.kun.security.facade.rpc.UserRoleResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.miotech.kun.security.facade.rpc.UserRoleResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.miotech.kun.security.facade.rpc.UserRoleResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.miotech.kun.security.facade.rpc.UserRoleResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.miotech.kun.security.facade.rpc.UserRoleResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.miotech.kun.security.facade.rpc.UserRoleResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.miotech.kun.security.facade.rpc.UserRoleResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UserRoleResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UserRoleResp)
      com.miotech.kun.security.facade.rpc.UserRoleRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.miotech.kun.security.facade.rpc.SecurityProto.internal_static_UserRoleResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.miotech.kun.security.facade.rpc.SecurityProto.internal_static_UserRoleResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.miotech.kun.security.facade.rpc.UserRoleResp.class, com.miotech.kun.security.facade.rpc.UserRoleResp.Builder.class);
    }

    // Construct using com.miotech.kun.security.facade.rpc.UserRoleResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getScopeRolesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      username_ = "";

      module_ = "";

      if (scopeRolesBuilder_ == null) {
        scopeRoles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        scopeRolesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.miotech.kun.security.facade.rpc.SecurityProto.internal_static_UserRoleResp_descriptor;
    }

    @java.lang.Override
    public com.miotech.kun.security.facade.rpc.UserRoleResp getDefaultInstanceForType() {
      return com.miotech.kun.security.facade.rpc.UserRoleResp.getDefaultInstance();
    }

    @java.lang.Override
    public com.miotech.kun.security.facade.rpc.UserRoleResp build() {
      com.miotech.kun.security.facade.rpc.UserRoleResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.miotech.kun.security.facade.rpc.UserRoleResp buildPartial() {
      com.miotech.kun.security.facade.rpc.UserRoleResp result = new com.miotech.kun.security.facade.rpc.UserRoleResp(this);
      int from_bitField0_ = bitField0_;
      result.username_ = username_;
      result.module_ = module_;
      if (scopeRolesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          scopeRoles_ = java.util.Collections.unmodifiableList(scopeRoles_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.scopeRoles_ = scopeRoles_;
      } else {
        result.scopeRoles_ = scopeRolesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.miotech.kun.security.facade.rpc.UserRoleResp) {
        return mergeFrom((com.miotech.kun.security.facade.rpc.UserRoleResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.miotech.kun.security.facade.rpc.UserRoleResp other) {
      if (other == com.miotech.kun.security.facade.rpc.UserRoleResp.getDefaultInstance()) return this;
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        onChanged();
      }
      if (!other.getModule().isEmpty()) {
        module_ = other.module_;
        onChanged();
      }
      if (scopeRolesBuilder_ == null) {
        if (!other.scopeRoles_.isEmpty()) {
          if (scopeRoles_.isEmpty()) {
            scopeRoles_ = other.scopeRoles_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureScopeRolesIsMutable();
            scopeRoles_.addAll(other.scopeRoles_);
          }
          onChanged();
        }
      } else {
        if (!other.scopeRoles_.isEmpty()) {
          if (scopeRolesBuilder_.isEmpty()) {
            scopeRolesBuilder_.dispose();
            scopeRolesBuilder_ = null;
            scopeRoles_ = other.scopeRoles_;
            bitField0_ = (bitField0_ & ~0x00000001);
            scopeRolesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getScopeRolesFieldBuilder() : null;
          } else {
            scopeRolesBuilder_.addAllMessages(other.scopeRoles_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.miotech.kun.security.facade.rpc.UserRoleResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.miotech.kun.security.facade.rpc.UserRoleResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object username_ = "";
    /**
     * <code>string username = 1;</code>
     * @return The username.
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string username = 1;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      username_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string username = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      
      username_ = getDefaultInstance().getUsername();
      onChanged();
      return this;
    }
    /**
     * <code>string username = 1;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      username_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object module_ = "";
    /**
     * <code>string module = 2;</code>
     * @return The module.
     */
    public java.lang.String getModule() {
      java.lang.Object ref = module_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        module_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string module = 2;</code>
     * @return The bytes for module.
     */
    public com.google.protobuf.ByteString
        getModuleBytes() {
      java.lang.Object ref = module_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        module_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string module = 2;</code>
     * @param value The module to set.
     * @return This builder for chaining.
     */
    public Builder setModule(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      module_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string module = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearModule() {
      
      module_ = getDefaultInstance().getModule();
      onChanged();
      return this;
    }
    /**
     * <code>string module = 2;</code>
     * @param value The bytes for module to set.
     * @return This builder for chaining.
     */
    public Builder setModuleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      module_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.miotech.kun.security.facade.rpc.ScopeRole> scopeRoles_ =
      java.util.Collections.emptyList();
    private void ensureScopeRolesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        scopeRoles_ = new java.util.ArrayList<com.miotech.kun.security.facade.rpc.ScopeRole>(scopeRoles_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.miotech.kun.security.facade.rpc.ScopeRole, com.miotech.kun.security.facade.rpc.ScopeRole.Builder, com.miotech.kun.security.facade.rpc.ScopeRoleOrBuilder> scopeRolesBuilder_;

    /**
     * <code>repeated .ScopeRole scopeRoles = 3;</code>
     */
    public java.util.List<com.miotech.kun.security.facade.rpc.ScopeRole> getScopeRolesList() {
      if (scopeRolesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(scopeRoles_);
      } else {
        return scopeRolesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ScopeRole scopeRoles = 3;</code>
     */
    public int getScopeRolesCount() {
      if (scopeRolesBuilder_ == null) {
        return scopeRoles_.size();
      } else {
        return scopeRolesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ScopeRole scopeRoles = 3;</code>
     */
    public com.miotech.kun.security.facade.rpc.ScopeRole getScopeRoles(int index) {
      if (scopeRolesBuilder_ == null) {
        return scopeRoles_.get(index);
      } else {
        return scopeRolesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ScopeRole scopeRoles = 3;</code>
     */
    public Builder setScopeRoles(
        int index, com.miotech.kun.security.facade.rpc.ScopeRole value) {
      if (scopeRolesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScopeRolesIsMutable();
        scopeRoles_.set(index, value);
        onChanged();
      } else {
        scopeRolesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ScopeRole scopeRoles = 3;</code>
     */
    public Builder setScopeRoles(
        int index, com.miotech.kun.security.facade.rpc.ScopeRole.Builder builderForValue) {
      if (scopeRolesBuilder_ == null) {
        ensureScopeRolesIsMutable();
        scopeRoles_.set(index, builderForValue.build());
        onChanged();
      } else {
        scopeRolesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ScopeRole scopeRoles = 3;</code>
     */
    public Builder addScopeRoles(com.miotech.kun.security.facade.rpc.ScopeRole value) {
      if (scopeRolesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScopeRolesIsMutable();
        scopeRoles_.add(value);
        onChanged();
      } else {
        scopeRolesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ScopeRole scopeRoles = 3;</code>
     */
    public Builder addScopeRoles(
        int index, com.miotech.kun.security.facade.rpc.ScopeRole value) {
      if (scopeRolesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScopeRolesIsMutable();
        scopeRoles_.add(index, value);
        onChanged();
      } else {
        scopeRolesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ScopeRole scopeRoles = 3;</code>
     */
    public Builder addScopeRoles(
        com.miotech.kun.security.facade.rpc.ScopeRole.Builder builderForValue) {
      if (scopeRolesBuilder_ == null) {
        ensureScopeRolesIsMutable();
        scopeRoles_.add(builderForValue.build());
        onChanged();
      } else {
        scopeRolesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ScopeRole scopeRoles = 3;</code>
     */
    public Builder addScopeRoles(
        int index, com.miotech.kun.security.facade.rpc.ScopeRole.Builder builderForValue) {
      if (scopeRolesBuilder_ == null) {
        ensureScopeRolesIsMutable();
        scopeRoles_.add(index, builderForValue.build());
        onChanged();
      } else {
        scopeRolesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ScopeRole scopeRoles = 3;</code>
     */
    public Builder addAllScopeRoles(
        java.lang.Iterable<? extends com.miotech.kun.security.facade.rpc.ScopeRole> values) {
      if (scopeRolesBuilder_ == null) {
        ensureScopeRolesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, scopeRoles_);
        onChanged();
      } else {
        scopeRolesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ScopeRole scopeRoles = 3;</code>
     */
    public Builder clearScopeRoles() {
      if (scopeRolesBuilder_ == null) {
        scopeRoles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        scopeRolesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ScopeRole scopeRoles = 3;</code>
     */
    public Builder removeScopeRoles(int index) {
      if (scopeRolesBuilder_ == null) {
        ensureScopeRolesIsMutable();
        scopeRoles_.remove(index);
        onChanged();
      } else {
        scopeRolesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ScopeRole scopeRoles = 3;</code>
     */
    public com.miotech.kun.security.facade.rpc.ScopeRole.Builder getScopeRolesBuilder(
        int index) {
      return getScopeRolesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ScopeRole scopeRoles = 3;</code>
     */
    public com.miotech.kun.security.facade.rpc.ScopeRoleOrBuilder getScopeRolesOrBuilder(
        int index) {
      if (scopeRolesBuilder_ == null) {
        return scopeRoles_.get(index);  } else {
        return scopeRolesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ScopeRole scopeRoles = 3;</code>
     */
    public java.util.List<? extends com.miotech.kun.security.facade.rpc.ScopeRoleOrBuilder> 
         getScopeRolesOrBuilderList() {
      if (scopeRolesBuilder_ != null) {
        return scopeRolesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(scopeRoles_);
      }
    }
    /**
     * <code>repeated .ScopeRole scopeRoles = 3;</code>
     */
    public com.miotech.kun.security.facade.rpc.ScopeRole.Builder addScopeRolesBuilder() {
      return getScopeRolesFieldBuilder().addBuilder(
          com.miotech.kun.security.facade.rpc.ScopeRole.getDefaultInstance());
    }
    /**
     * <code>repeated .ScopeRole scopeRoles = 3;</code>
     */
    public com.miotech.kun.security.facade.rpc.ScopeRole.Builder addScopeRolesBuilder(
        int index) {
      return getScopeRolesFieldBuilder().addBuilder(
          index, com.miotech.kun.security.facade.rpc.ScopeRole.getDefaultInstance());
    }
    /**
     * <code>repeated .ScopeRole scopeRoles = 3;</code>
     */
    public java.util.List<com.miotech.kun.security.facade.rpc.ScopeRole.Builder> 
         getScopeRolesBuilderList() {
      return getScopeRolesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.miotech.kun.security.facade.rpc.ScopeRole, com.miotech.kun.security.facade.rpc.ScopeRole.Builder, com.miotech.kun.security.facade.rpc.ScopeRoleOrBuilder> 
        getScopeRolesFieldBuilder() {
      if (scopeRolesBuilder_ == null) {
        scopeRolesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.miotech.kun.security.facade.rpc.ScopeRole, com.miotech.kun.security.facade.rpc.ScopeRole.Builder, com.miotech.kun.security.facade.rpc.ScopeRoleOrBuilder>(
                scopeRoles_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        scopeRoles_ = null;
      }
      return scopeRolesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:UserRoleResp)
  }

  // @@protoc_insertion_point(class_scope:UserRoleResp)
  private static final com.miotech.kun.security.facade.rpc.UserRoleResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.miotech.kun.security.facade.rpc.UserRoleResp();
  }

  public static com.miotech.kun.security.facade.rpc.UserRoleResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserRoleResp>
      PARSER = new com.google.protobuf.AbstractParser<UserRoleResp>() {
    @java.lang.Override
    public UserRoleResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserRoleResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserRoleResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserRoleResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.miotech.kun.security.facade.rpc.UserRoleResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

