package com.miotech.kun.operationrecord.common.model;

public enum OperationRecordType {

    TASK_DEFINITION_CREATE
    , TASK_DEFINITION_UPDATE
    , TASK_DEFINITION_DELETE
    , TASK_DEFINITION_DEPLOY

    , TASK_VIEW_CREATE
    , TASK_VIEW_UPDATE
    , TASK_VIEW_DELETE

    , TASK_BACKFILL_CREATE_RUN
    , TASK_BACKFILL_RUN
    , TASK_BACKFILL_ABORT
    , TASK_BACKFILL_TASKRUN_RESTART
    , TASK_BACKFILL_TASKRUN_ABORT

    , TASK_RERUN
    , TASK_ABORT
    , TASK_SKIP
    , TASK_REMOVE_DEPENDENCY

    , GLOSSARY_CREATE
    , GLOSSARY_UPDATE
    , GLOSSARY_DELETE
    , GLOSSARY_COPY_PASTE
    , GLOSSARY_UPDATE_GRAPH
    , GLOSSARY_ADD_OWNER
    , GLOSSARY_REMOVE_OWNER
    , GLOSSARY_ADD_RESOURCE
    , GLOSSARY_REMOVE_RESOURCE

    , DATASET_UPDATE
    , DATASET_PULL
    , DATASET_UPDATE_COLUMN

    , DATASOURCE_ADD
    , DATASOURCE_UPDATE
    , DATASOURCE_DELETE
    , DATASOURCE_PULL

    , EXPECTATION_CREATE
    , EXPECTATION_UPDATE
    , EXPECTATION_DELETE

    , WORKFLOW_SET_MAINTENANCE_MODE
    ;

}
