apiVersion: v1
kind: Pod
metadata:
  labels:
    kun-workflow: "kun-workflow"
    kuntaskattemptid: "167906031635005441"
  name: "kunworkflow167906031635005441"
spec:
  containers:
    - image: nopoperator
      imagePullPolicy: IfNotPresent
      name: kunnopoperator
      command: [ "java",  "-XX:+PrintGCDetails", "-XX:+HeapDumpOnOutOfMemoryError", "-jar","/server/target/kubernetesOperatorLauncher.jar" ]
      env:
        - name: logPath
          value: "file:/Users/shiki/kubeLog/167906031635005441"
        - name: className
          value: "NopOperator"
        - name: taskRunId
          value: "167906031635005440"
        - name: taskAttemptId
          value: "167906031635005441"
        - name: jarPath
          value: "file:/server/libs/NopOperator.jar"
        - name: configKey
          value: ""
  restartPolicy: Never