#services:
#  - hub.miotech.com/mioyingtech/kun-workflow:master
#
#variables:
#  SERVER_PORT: 8088
#  APP_CONFIG_ENV: local

#verify-kun-data-platform-test:
#  extends: .build-kun-data-platform
#  stage: verify
#  image: gradle:6.5.0-jdk8
#  except:
#    - master
#    - release
#    - production
#    - tags
#  allow_failure: false
#  script:
#    - cat /root/.docker/config.json
#    - export DOCKER_CONFIG=/root/.docker
#    - ./gradlew check -p kun-data-platform
#
#verify-kun-data-platform-sonar:
#  extends: .build-kun-data-platform
#  stage: verify
#  image: mioyingtech/gradle-sonar:0.1-build
#  except:
#    - release
#    - production
#    - tags
#  allow_failure: false
#  script:
#    - >
#      if [ $CI_COMMIT_REF_NAME == "master" ]; then
#          ./gradlew sonarqube -p kun-data-platform -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_TOKEN -Dsonar.analysis.mode=publish -Dsonar.issuesReport.html.enable=true -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.projectKey=com.miotech:kun-data-platform -Dsonar.projectName='kun-data-platform';
#      else ./gradlew sonarqube -p kun-data-platform -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_TOKEN -Dsonar.analysis.mode=preview -Dsonar.issuesReport.html.enable=true -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.projectKey=com.miotech:kun-data-platform -Dsonar.projectName='kun-data-platform';
#      fi

kun-data-platform-build:
  extends: .build-kun-data-platform
  stage: build
  image: gradle:6.5.0-jdk8
  tags:
    - build
  script:
    - ./gradlew :kun-data-platform:bootJar
    - mkdir -p /builds/artifacts/kun-data-platform/${CI_COMMIT_REF_NAME}/
    - cp kun-data-platform/build/libs/*.jar /builds/artifacts/kun-data-platform/${CI_COMMIT_REF_NAME}/
  only:
    refs:
      - master
      - release
      - /.*v(\d{0,3})+(\.\d{0,3})+(\.\d{0,3})+\-kun-data-platform\-([1-9]\d{0,3}).*$/

kun-data-platform-push:
  extends: .build-kun-data-platform
  image: mioyingtech/docker:latest
  stage: build-images
  tags:
    - docker-push
  script:
    - mkdir -p /builds/kun-data-platform/build/libs/
    - rsync -vzrtopg --progress -e ssh root@$CI_RUNNER_SERVER:/miotech/artifacts/kun-data-platform/${CI_COMMIT_REF_NAME}/ /builds/kun-data-platform/build/libs/
    - docker login -u $CI_BUILD_DOCKER_USER -p $CI_BUILD_TOKEN $CI_BUILD_DOCKER_URL
    - docker build -t ${CI_BUILD_DOCKER_URL}mioyingtech/kun-data-platform:$CI_COMMIT_REF_NAME /builds/kun-data-platform/
    - docker push ${CI_BUILD_DOCKER_URL}mioyingtech/kun-data-platform:$CI_COMMIT_REF_NAME
  only:
    refs:
      - master
      - release
      - /.*v(\d{0,3})+(\.\d{0,3})+(\.\d{0,3})+\-kun-data-platform\-([1-9]\d{0,3}).*$/

kun-data-platform-set-tag:
  extends: .build-kun-data-platform
  stage: set-tag
  tags:
    - build
  image: mioyingtech/python-gitlab:0.1-build
  script:
    - python /tmp/tag.py --projectId $CI_PROJECT_ID --branchName $CI_COMMIT_REF_NAME --privateToken $CI_GITLAB_TOKEN --gitlabUrl $GITLAB_URL --serviceName kun-data-platform
  only:
    refs:
      - production
      
kun-data-platform-set-tag-hotfix:
  extends: .build-kun-data-platform
  stage: set-tag
  tags:
    - build
  image: mioyingtech/python-gitlab:0.1-build
  script:
    - python /tmp/tag.py --projectId $CI_PROJECT_ID --branchName $CI_COMMIT_REF_NAME --privateToken $CI_GITLAB_TOKEN --gitlabUrl $GITLAB_URL --serviceName kun-data-platform
  only:
    refs:
      - /^HOTFIX+.*/
  when: manual

kun-data-platform-save-tag:
  extends: .build-kun-data-platform
  stage: save-tag
  tags:
    - build
  image: mioyingtech/python-gitlab:0.1-build
  only:
    - /.*v(\d{0,3})+(\.\d{0,3})+(\.\d{0,3})+\-kun-data-platform\-([1-9]\d{0,3}).*$/
  script:
    - python /tmp/saveTag.py --appName=kun-data-platform --tag=${CI_COMMIT_REF_NAME}
  allow_failure: true