server:
  port: ${KUN_APP_PORT}

workflow:
  enabled: true
  base-url: http://${KUN_INFRA_HOST}:${KUN_INFRA_PORT}
  variable-namespace: dataplatform

spring:
  datasource:
    postgresql:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${DB_PG_IP}:${DB_PG_PORT}/kun?stringtype=unspecified
      username: ${DB_PG_USERNAME}
      password: ${DB_PG_PASSWORD}

    neo4j:
      driver-class-name: org.neo4j.jdbc.bolt.BoltDriver
      url: jdbc:neo4j:bolt://${DB_NEO4J_IP}:${DB_NEO4J_PORT}
      username: ${DB_NEO4J_USERNAME}
      password: ${DB_NEO4J_PASSWORD}

  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:webapp_sql
    table: flyway_kun_webapp_schema_history
    schemas: public
    baselineOnMigrate: true
    baselineVersion: 0

  session:
    jdbc:
      initialize-schema: never
      table-name: kun_user_session
    timeout: 30d

security:
  base-url: http://${SECURITY_HOST}:${SECURITY_PORT}/kun/api/v1

infra:
  base-url: http://${KUN_INFRA_HOST}:${KUN_INFRA_PORT}

redis:
  host: ${DB_REDIS_IP}
  notify-channel: kun-notify
  stream-key: kun-notify
  operation-record:
    group: operation-record-group
    consumer: operation-record-consumer
  data-quality:
    group: data-quality-group
    consumer: data-quality-consumer
  alert:
    group: alert-group
    consumer: alert-consumer
  sla:
    group: sla-group
    consumer: sla-consumer

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    elasticsearch:
      enabled: false
    ldap:
      enabled: false
    db:
      enabled: false

# Notification configurations items
notify:
  # System default configurations to be applied for default task definitions.
  systemDefault:
    # Allowed trigger types: ON_SUCCESS, ON_FAIL, ON_FINISH, NEVER
    triggerType: ON_FAIL
    userConfigJson: '[{"notifierType": "EMAIL"}]'
  # Email notifier settings
  email:
    # For developers, usually, we do not spend extra time on configuring these SMTP connection settings
    enabled: ${EMAIL_NOTIFIER_ENABLED:false}
    # Host of SMTP server to connect
    smtpHost: ${SMTP_HOST:}
    # Port of SMTP server to connect
    smtpPort: ${SMTP_PORT:465}
    # Username of SMTP server to connect
    smtpUsername: ${SMTP_USERNAME:}
    # Password of SMTP server to connect
    smtpPassword: ${SMTP_PASSWORD:}
    # Connection transmission security protocol. Available options: auto (default), ssl_tls, starttls, none.
    # When set to "auto", the application will automatically determine which security protocol to use by smtp port number.
    smtpSecurity: ${SMTP_SECURITY_PROTOCOL:auto}
    # Displayed email address of sending from
    emailFrom: ${EMAIL_FROM:noreply@miotech.com}
    # Displayed name of sending from
    emailFromName: ${EMAIL_FROM_NAME:kun-robot}
  # Decide whether notification content contains issue link URL, if possible
  urlLink:
    enabled: ${NOTIFY_URL_LINK_ENABLED:true}
    # Your web link host url prefix in format of {PROTOCOL}://{HOST}[:PORT]. For instance, "https://kun.miotech.com", "http://127.0.0.1:12345", etc.
    prefix: ${NOTIFY_URL_LINK_PREFIX:http://localhost:9801}

  wecom:
    corpid: 123
    corpsecret: abc
    agentid: 1
    chatid: 1
    url:
      get_token: https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=%s&corpsecret=%s
      send-to-user: https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=%s
      send-to-chat: https://qyapi.weixin.qq.com/cgi-bin/appchat/send?access_token=%s

data-dashboard:
  long-existing-threshold: 30

# Data-discovery config

metadata:
  base-url: http://${KUN_INFRA_HOST}:${KUN_INFRA_PORT}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_PG_IP}:${DB_PG_PORT}/kun?stringtype=unspecified
    username: ${DB_PG_USERNAME}
    password: ${DB_PG_PASSWORD}

data-quality:
  workflow:
    task:
      cron: 0 0 0 * * ?
  daily:
    start: 0 0 1 * * ?
  hooks:
    check-hook:
      classname: com.miotech.kun.dataquality.web.hook.HudiDataQualityCheckHook
      params:
        warehouse-url: warehourse
        access-key: accesskey
        secrey-key: secreykey
    operator-check-hook:
      classname: com.miotech.kun.workflow.operator.hook.HudiDataQualityCheckOperatorHook
      params:
        warehouse-url: warehourse
        access-key: accesskey
        secrey-key: secreykey


springdoc:
  swagger-ui:
    operationsSorter: method
  use-fqn: true

spark:
  thrift-server:
    enabled: false
    url:
    username:
    password:

grpc:
  server:
    security-host: ${SECURITY_HOST}
    port: ${WORKFLOW_RPC_SERVICE_PORT}
discovery:
  enabled: true
rdm:
  aws:
    access-key: rdm_test_accessKey
    secret-key: rdm_test_secretKey
    region: test_region
  bucket-name: test.ref.data
  database-name: ref_test

