alter table kun_dq_case drop constraint kun_dq_case_kun_dq_case_datasource_template_id_fk;

alter table kun_dq_case_associated_dataset drop constraint kun_dq_case_associated_dataset_kun_dq_case_id_fk;

alter table kun_dq_case_associated_dataset drop constraint kun_dq_case_associated_dataset_kun_mt_dataset_gid_fk;

alter table kun_dq_case_associated_dataset_field drop constraint kun_dq_case_associated_dataset_field_case_id_fk;

alter table kun_dq_case_associated_dataset_field drop constraint kun_dq_case_associated_dataset_field_dataset_field_id_fk;

alter table kun_dq_case_datasource_template drop constraint kun_dq_case_datasource_template_template_id_fk;

alter table kun_dq_case_datasource_template drop constraint kun_dq_case_datasource_template_datasource_type_id_fk;

alter table kun_dq_case_rules drop constraint kun_dq_case_rules_kun_dq_case_id_fk;

alter table kun_mt_dataset_attrs drop constraint kun_mt_dataset_attrs_kun_mt_dataset_gid_fk;

alter table kun_mt_dataset_owners drop constraint kun_mt_dataset_owners_kun_mt_dataset_gid_fk;

alter table kun_mt_dataset_tags drop constraint kun_mt_dataset_tags_kun_mt_dataset_gid_fk;

alter table kun_mt_datasource drop constraint kun_mt_datasource_kun_mt_datasource_type_id_fk;

alter table kun_mt_datasource_attrs drop constraint kun_mt_datasource_attrs_kun_mt_datasource_id_fk;

alter table kun_mt_datasource_tags drop constraint kun_mt_datasource_tags_kun_mt_datasource_id_fk;

alter table kun_mt_datasource_type_fields drop constraint kun_mt_datasource_type_fields_kun_mt_datasource_type_id_fk;

alter table kun_mt_glossary drop constraint kun_mt_glossary_kun_mt_glossary_id_fk;

alter table kun_mt_glossary_to_dataset_ref drop constraint kun_mt_glossary_to_dataset_ref_kun_mt_glossary_id_fk;

alter table kun_mt_glossary_to_dataset_ref drop constraint kun_mt_glossary_to_dataset_ref_kun_mt_dataset_gid_fk;
