server:
  port: ${DATA_DISCOVERY_PORT}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_PG_IP}:${DB_PG_PORT}/kun
    username: ${DB_PG_USERNAME}
    password: ${DB_PG_PASSWORD}

  session:
    jdbc:
      initialize-schema: never
      table-name: kun_user_session
    timeout: 30d

  flyway:
    # 启用或禁用 flyway
    enabled: true
    # flyway 的 clean 命令会删除指定 schema 下的所有 table, 生产务必禁掉。这个默认值是 false 理论上作为默认配置是不科学的。
    clean-disabled: true
    # SQL 脚本的目录,多个路径使用逗号分隔 默认值 classpath:db/migration
    locations: classpath:db/migration
    # metadata 版本控制信息表 默认 flyway_schema_history
    table: flyway_kun_app_schema_history
    # 如果没有 flyway_schema_history 这个 metadata 表， 在执行 flyway migrate 命令之前, 必须先执行 flyway baseline 命令
    # 设置为 true 后 flyway 将在需要 baseline 的时候, 自动执行一次 baseline。
    baseline-on-migrate: true
    # 指定 baseline 的版本号,默认值为 1, 低于该版本号的 SQL 文件, migrate 时会被忽略
    baseline-version: 0
    # 字符编码 默认 UTF-8
    encoding: UTF-8
    # 是否允许不按顺序迁移 开发建议 true  生产建议 false
    out-of-order: false
    # 需要 flyway 管控的 schema list,这里我们配置为flyway  缺省的话, 使用spring.datasource.url 配置的那个 schema,
    # 可以指定多个schema, 但仅会在第一个schema下建立 metadata 表, 也仅在第一个schema应用migration sql 脚本.
    # 但flyway Clean 命令会依次在这些schema下都执行一遍. 所以 确保生产 spring.flyway.clean-disabled 为 true
    schemas: public
    # 执行迁移时是否自动调用验证   当你的 版本不符合逻辑 比如 你先执行了 DML 而没有 对应的DDL 会抛出异常
    validate-on-migrate: true

security:
  auth:
    type: ${SECURITY_AUTH_TYPE:JSON}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_PG_IP}:${DB_PG_PORT}/kun
    username: ${DB_PG_USERNAME}
    password: ${DB_PG_PASSWORD}

metadata:
  base-url: http://${METADATA_HOST}:${METADATA_PORT}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_PG_IP}:${DB_PG_PORT}/kun
    username: ${DB_PG_USERNAME}
    password: ${DB_PG_PASSWORD}

workflow:
  base-url: http://${WORKFLOW_HOST}:${WORKFLOW_PORT}

data-quality:
  workflow:
    task:
      cron: 0 0 0 * * ?

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    ldap:
      enabled: false