server:
  port: ${SECURITY_PORT}

spring:
  datasource:
    driver-class-name: org.neo4j.jdbc.bolt.BoltDriver
    url: jdbc:neo4j:bolt://${DB_NEO4J_IP}:7687
    username: ${DB_NEO4J_USERNAME}
    password: ${DB_NEO4J_PASSWORD}

  session:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${DB_PG_IP}:${DB_PG_PORT}/kun_security
      username: ${DB_PG_USERNAME}
      password: ${DB_PG_PASSWORD}
    jdbc:
      initialize-schema: always
    timeout: 30d

  flyway:
    enabled: false

  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: ***REMOVED***
            client-secret: ***REMOVED***
        provider:
          okta:
            authorization-uri: https://dev-7959592.okta.com/oauth2/v1/authorize
            token-uri: https://dev-7959592.okta.com/oauth2/v1/token
            user-info-uri: https://dev-7959592.okta.com/oauth2/v1/userinfo
            jwk-set-uri: https://dev-7959592.okta.com/oauth2/v1/keys

security:
  auth:
    type: ${SECURITY_AUTH_TYPE:DAO}

liquigraph:
  change-log: classpath:security/db/migration/changelog.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: false
    ldap:
      enabled: false