server:
  port: ${SECURITY_PORT}

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.neo4j.Neo4jAutoConfiguration
  datasource:
    driver-class-name: org.neo4j.jdbc.bolt.BoltDriver
    url: jdbc:neo4j:bolt://${DB_NEO4J_IP}:7687
    username: ${DB_NEO4J_USERNAME}
    password: ${DB_NEO4J_PASSWORD}

  session:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${DB_PG_IP}:${DB_PG_PORT}/kun_security
      username: ${DB_PG_USERNAME}
      password: ${DB_PG_PASSWORD}
    jdbc:
      initialize-schema: always
    timeout: 30d

  flyway:
    enabled: false

  security:
    oauth2:
      client:
        enable: ${SECURITY_OAUTH2_CLIENT_ENABLE:false}
        registration:
          okta:
            client-id: 0oa37lfa3y3QbRy1c5d6
            client-secret: I7ToFyyRrAF5yLSRChda7jvcmU-xcz41G-zaz_ot
            redirect-uri: http://localhost:9801/sso
        provider:
          okta:
            authorization-uri: https://dev-7959592.okta.com/oauth2/v1/authorize
            token-uri: https://dev-7959592.okta.com/oauth2/v1/token
            user-info-uri: https://dev-7959592.okta.com/oauth2/v1/userinfo
            jwk-set-uri: https://dev-7959592.okta.com/oauth2/v1/keys
    saml2:
      enable: true
      relyingparty:
        authorityMapping:
          okta: Groups
        identityMapping:
          okta:
            givenName: FirstName
            familyName: LastName
            email: Email
        registration:
          okta:
            acs:
              location: http://localhost:8079/api/login/saml2/sso/okta
            entity-id: http://localhost.miotech.com/saml2/service-provider-metadata/{registrationId}
            identityprovider:
              metadata-uri: https://dev-7959592.okta.com/app/exkb49nl6sfYtNTwV5d6/sso/saml/metadata

security:
  auth:
    type: ${SECURITY_AUTH_TYPE:DAO}

liquigraph:
  change-log: classpath:security/db/migration/changelog.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    elasticsearch:
      enabled: false
    db:
      enabled: false
    ldap:
      enabled: false

springdoc:
  swagger-ui:
    operationsSorter: method
  use-fqn: true

frontend:
  url: ${KUN_ROOT_URL:http://localhost:8079}