server:
  port: ${SECURITY_PORT}

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.neo4j.Neo4jAutoConfiguration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_PG_IP}:${DB_PG_PORT}/kun?stringtype=unspecified
    username: ${DB_PG_USERNAME}
    password: ${DB_PG_PASSWORD}

  session:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${DB_PG_IP}:${DB_PG_PORT}/kun?stringtype=unspecified
      username: ${DB_PG_USERNAME}
      password: ${DB_PG_PASSWORD}
    jdbc:
      initialize-schema: always
    timeout: 30d

  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:security_sql
    table: flyway_kun_security_schema_history
    schemas: public
    baselineOnMigrate: true
    baselineVersion: 0
    validate-on-migrate: false

  security:
    oauth2:
      client:
        enable: ${SECURITY_OAUTH2_CLIENT_ENABLE:false}
        registration:
          okta:
            client-id: ${SECURITY_OAUTH2_CLIENT_ID}
            client-secret: ${SECURITY_OAUTH2_CLIENT_SECRET}
            redirect-uri: http://localhost:9801/sso
        provider:
          okta:
            authorization-uri: https://dev-7959592.okta.com/oauth2/v1/authorize
            token-uri: https://dev-7959592.okta.com/oauth2/v1/token
            user-info-uri: https://dev-7959592.okta.com/oauth2/v1/userinfo
            jwk-set-uri: https://dev-7959592.okta.com/oauth2/v1/keys
    saml2:
      enable: true
      relyingparty:
        authorityMapping:
          okta: Groups
        identityMapping:
          okta:
            givenName: FirstName
            familyName: LastName
            email: Email
        registration:
          okta:
            acs:
              location: http://localhost:8079/api/login/saml2/sso/okta
            entity-id: http://localhost.miotech.com/saml2/service-provider-metadata/{registrationId}
            identityprovider:
              metadata-uri: https://dev-7959592.okta.com/app/exkb49nl6sfYtNTwV5d6/sso/saml/metadata

security:
  auth:
    type: ${SECURITY_AUTH_TYPE:DAO}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    elasticsearch:
      enabled: false
    db:
      enabled: false
    ldap:
      enabled: false

springdoc:
  swagger-ui:
    operationsSorter: method
  use-fqn: true

frontend:
  url: ${KUN_ROOT_URL:http://localhost:8079}
