INSERT INTO public.kun_mt_datasource_type (id, name) VALUES (1, 'AWS');
INSERT INTO public.kun_mt_datasource_type (id, name) VALUES (2, 'MongoDB');
INSERT INTO public.kun_mt_datasource_type (id, name) VALUES (3, 'PostgreSQL');
INSERT INTO public.kun_mt_datasource_type (id, name) VALUES (4, 'Elasticsearch');
INSERT INTO public.kun_mt_datasource_type (id, name) VALUES (5, 'Arango');

INSERT INTO public.kun_mt_datasource_type_fields (id, type_id, name, sequence_order, format) VALUES (1, 2, 'host', 1, 'INPUT');
INSERT INTO public.kun_mt_datasource_type_fields (id, type_id, name, sequence_order, format) VALUES (2, 2, 'port', 2, 'INPUT');
INSERT INTO public.kun_mt_datasource_type_fields (id, type_id, name, sequence_order, format) VALUES (3, 2, 'username', 3, 'INPUT');
INSERT INTO public.kun_mt_datasource_type_fields (id, type_id, name, sequence_order, format) VALUES (4, 2, 'password', 4, 'INPUT');
INSERT INTO public.kun_mt_datasource_type_fields (id, type_id, name, sequence_order, format) VALUES (5, 3, 'host', 1, 'INPUT');
INSERT INTO public.kun_mt_datasource_type_fields (id, type_id, name, sequence_order, format) VALUES (6, 3, 'port', 2, 'INPUT');
INSERT INTO public.kun_mt_datasource_type_fields (id, type_id, name, sequence_order, format) VALUES (7, 3, 'username', 3, 'INPUT');
INSERT INTO public.kun_mt_datasource_type_fields (id, type_id, name, sequence_order, format) VALUES (8, 3, 'password', 4, 'INPUT');
INSERT INTO public.kun_mt_datasource_type_fields (id, type_id, name, sequence_order, format) VALUES (9, 4, 'host', 1, 'INPUT');
INSERT INTO public.kun_mt_datasource_type_fields (id, type_id, name, sequence_order, format) VALUES (10, 4, 'athenaUrl', 2, 'INPUT');
INSERT INTO public.kun_mt_datasource_type_fields (id, type_id, name, sequence_order, format) VALUES (11, 4, 'username', 3, 'INPUT');
INSERT INTO public.kun_mt_datasource_type_fields (id, type_id, name, sequence_order, format) VALUES (12, 4, 'glueAccessKey', 4, 'INPUT');
INSERT INTO public.kun_mt_datasource_type_fields (id, type_id, name, sequence_order, format) VALUES (13, 5, 'host', 1, 'INPUT');
INSERT INTO public.kun_mt_datasource_type_fields (id, type_id, name, sequence_order, format) VALUES (14, 5, 'port', 2, 'INPUT');
INSERT INTO public.kun_mt_datasource_type_fields (id, type_id, name, sequence_order, format) VALUES (15, 5, 'username', 3, 'INPUT');
INSERT INTO public.kun_mt_datasource_type_fields (id, type_id, name, sequence_order, format) VALUES (16, 5, 'password', 4, 'INPUT');
INSERT INTO public.kun_mt_datasource_type_fields (id, type_id, name, sequence_order, format) VALUES (17, 1, 'glueAccessKey', 1, 'INPUT');
INSERT INTO public.kun_mt_datasource_type_fields (id, type_id, name, sequence_order, format) VALUES (18, 1, 'glueSecretKey', 2, 'INPUT');
INSERT INTO public.kun_mt_datasource_type_fields (id, type_id, name, sequence_order, format) VALUES (19, 1, 'glueRegion', 3, 'INPUT');
INSERT INTO public.kun_mt_datasource_type_fields (id, type_id, name, sequence_order, format) VALUES (20, 1, 'athenaUrl', 4, 'INPUT');
INSERT INTO public.kun_mt_datasource_type_fields (id, type_id, name, sequence_order, format) VALUES (21, 1, 'athenaUsername', 5, 'INPUT');
INSERT INTO public.kun_mt_datasource_type_fields (id, type_id, name, sequence_order, format) VALUES (22, 1, 'athenaPassword', 6, 'INPUT');

INSERT INTO public.kun_mt_datasource VALUES (1, null, 3);
INSERT INTO public.kun_mt_dataset VALUES (1, 'test.dataset-1', 1, null, null);
INSERT INTO public.kun_mt_dataset_attrs VALUES (1, 'dataset-1');
INSERT INTO public.kun_mt_dataset_field VALUES (1, 1, 'column-1', 'VARCHAR', '', 'VARCHAR');