name: infra test

on:
  pull_request:
    paths:
env:
  LOG_DIR: /tmp/kun-scheduler

jobs:

  verify:
    name: infra test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      # In the checkout@v2, it doesn't support git submodule. Execute the commands manually.
      - name: checkout submodules
        shell: bash
        run: |
          git submodule sync --recursive
          git -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: test
        run: |
          ./gradlew check -p kun-workflow
          ./gradlew check -p kun-metadata
      - name: Upload coverage report to codecov
        run: |
          CODECOV_TOKEN="c9895fa5-02da-4cf0-9f1b-fb66e47ea1c6" bash <(curl -s https://codecov.io/bash)
      # Set up JDK 11 for SonarCloud.
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Run SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonarqube -p kun-workflow --info
          ./gradlew sonarqube -p kun-metadata --info
