name: DATA DISCOVERY CI PULL REQUEST ACTIONS

on:
  push:
    paths:
      - 'kun-data-discovery/**'
      - 'kun-app-common/**'
      - 'kun-commons/**'
      - 'kun-data-quality/**'
      - 'kun-security/kun-security-common/**'
      - 'kun-workflow/kun-workflow-client/**'
      - 'kun-workflow/kun-workflow-core/**'
      - 'kun-workflow/kun-workflow-utils/**'
    branches-ignore:
      - master

jobs:
  step-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check with Gradle
        run: ./gradlew check -p kun-data-discovery
