name: FRONTEND CI PULL REQUEST ACTIONS

on:
  push:
    paths:
      - 'kun-frontend/**'

jobs:
  step-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Yarn install with Gradle
        run: ./gradlew kun-frontend:yarn_install
      - name: Check with Gradle
        run: ./gradlew kun-frontend:check
