name: SECURITY CI MASTER ACTIONS

on:
  workflow_dispatch:
    name:
      description: 'Person to greet'
      required: true
      default: 'Some Person'
  push:
    paths:
      - 'kun-app-common/**'
      - 'kun-security/**'
    branches:
      - master

jobs:
  step-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew kun-security:kun-security-server:bootJar
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: miotechoss/kun-security
          tags: master
          path: kun-security
